### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by guoqian0097282** [LiuLimingCode/HFNet_SLAM#1]
After initial, It can   Segmentation fault (core dumped) in GlobalBundleAdjustemnt and PoseOptimization. Why?
export model :
python export_model.py ../../HFNet_VINO/hfnet_ckpt/hfnet/  saved 5
run project:
./Examples/Monocular/mono_euroc ./Examples/Monocular/EuRoC.yaml ./evaluation/MH01_MONO/   /home/gq/guoqian/data/MH_01_easy/ ./Examples/Monocular/EuRoC_TimeStamps/MH01.txt

anything wrong?

**Comment by LiuLimingCode** [comment]
Sorry, I am currently busy with job recruitment. I don't have time for this project. I will figure out your problem after a month.
You can contact me with QQ: 1104257233, WeChat: liu1104257233 (刘力铭)

**Comment by Amrmesi** [comment]
I have the same issue if you've solved it please tell me how
