### ISSUE TITLE
编译成功，运行核心已转储

### ISSUE THREAD

**Issue by Dongdong-NEU** [LiuLimingCode/HFNet_SLAM#7]
感谢liming开源的代码～
我总共编译成功过两次。

第一次编译算法的时候用的CUDA, and cuDNN, TensorRT和提供的版本一致，opencv用的3.3.1（CV_OVERRIDE编译不过去改成overrid编过去了）。
运行的时候主要有这些警告或错误提示：
1. 关于TensorRT缓存结果无效的警告
2. 还有一个关于TensorRT与cuDNN版本不匹配的消息。Tensorrt与Cudnn 8.6.0相连，但加载了Cudnn 8.4.1，这应该是对的吧，加载的和要求的一致。 tensorrt的安装方式就是下载压缩包解压后把头文件和库文件放到指定地方：
`sudo cp -r ./lib/* /usr/lib
sudo cp -r ./include/* /usr/include
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lthpc/tensorrt_tar/TensorRT-8.5.1/lib`
3. 我运行了几次都不成功，偶尔会提示double free
![image](https://github.com/LiuLimingCode/HFNet_SLAM/assets/84561374/f77e3367-8217-4a23-9103-49ad8d7da4eb)
警告摘要：
WARNING: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
WARNING: onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Loaded 2215767 bytes of timing cache from /home/xhd/HFNet_SLAM-main/HFNet-RT/HF-Net.cache
WARNING: TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.4.1
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/Conv/Conv2D + PWN(pred/MobilenetV2/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0xc2a5fc6b5e7cef5e
...
...
Successfully loaded HFNet TensorRT model. Mode: ImageToLocal Shape: [1, 278, 435, 1]
Initialization of Atlas from scratch 
Creation of new map with id: 0
Creation of new map with last KF id: 0
There are 1 cameras in the atlas
Camera 0 is pinhole
Gtk-Message: 08:58:54.767: Failed to load module "canberra-gtk-module"
Starting the Viewer
First KF:0; Map init KF:0
New Map created with 481 points
Init frame id: 0
段错误 (核心已转储)

    这是完整的log文件：
[log.txt](https://github.com/LiuLimingCode/HFNet_SLAM/files/12326324/log.txt)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
按照提示，我以为cuda和cudnn和tensorrt有些不匹配，于是我多安装了cuda11.8和cudnn8.6，重新编译代码成功，
但很遗憾还是不能运行，下面是log
有几个新错误出现：

ERROR: 1: [myelinCache.h::deserializeFromBuffer::52] Error Code 1: Myelin (Myelin error from unknown graph)
ERROR: 4: The timing cache will not be used!`
ERROR: 2: [timingCache.cpp::addOp::492] Error Code 2: Internal Error (Assertion item.bestWorkSpace == i.bestWorkSpace failed. )
ERROR: 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
------------------
./Examples/Monocular/mono_euroc      ./Examples/Monocular/EuRoC.yaml      ./evaluation/Euroc      /media/xhd/新加卷/数据集/Euroc/MH01      ./Examples/Monocular/EuRoC_TimeStamps/MH01.txt
num_seq = 1
settings path: ./Examples/Monocular/EuRoC.yaml
result save path: ./evaluation/Euroc/
Loading images for sequence 0...LOADED!

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular
Loading settings from ./Examples/Monocular/EuRoC.yaml
Camera1.k3 optional parameter does not exist...
        -Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
        -Loaded image info
        -Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
        -Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
        -Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
        -Loaded misc parameters

SLAM settings: 
        -Camera 1 parameters (Pinhole): [ 458.65399169921875 457.29598999023438 367.21499633789062 248.375 ]
        -Camera 1 distortion parameters: [  -0.28340810537338257 0.073959067463874817 0.00019359000725671649 1.7618711353861727e-05 ]
        -Original image size: [ 752 , 480 ]
        -Current image size: [ 752 , 480 ]
        -Sequence FPS: 20
        -Scale factor of image pyramid: 1.2000000476837158
        -Levels of image pyramid: 4
        -Features per image: 675
        -Detector threshold: 0.0099999997764825821
        -Load model path: /home/xhd/HFNet_SLAM-main/HFNet-RT

WARNING: CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
WARNING: onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Loaded 2217379 bytes of timing cache from /home/xhd/HFNet_SLAM-main/HFNet-RT/HF-Net.cache
ERROR: 1: [myelinCache.h::deserializeFromBuffer::52] Error Code 1: Myelin (Myelin error from unknown graph)
ERROR: 4: The timing cache will not be used!
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/Conv/Conv2D + PWN(pred/MobilenetV2/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0xc2a5fc6b5e7cef5e
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/Conv/Conv2D + PWN(pred/MobilenetV2/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x94dc70026a3bd827
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/Conv/Conv2D + PWN(pred/MobilenetV2/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0xd15fd3ec25fa5e84
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/Conv/Conv2D + PWN(pred/MobilenetV2/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x49e0395ec5fc8474
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x6aaac747558eb868
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x69501656100171de
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/expand/Conv2D + pred/MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_1/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x5e7d1125e7896624
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/expand/Conv2D + pred/MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_1/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x849891f3d1d80c55
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/expand/Conv2D + pred/MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_1/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/expand/Conv2D + pred/MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_1/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/expand/Conv2D + pred/MobilenetV2/expanded_conv_1/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_1/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xdc559b3944b0cdf8
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_1/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xe5e256a48aae2e77
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_1/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x0129597ad9bbff14
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/expand/Conv2D + pred/MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_2/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x5e7d1125e7896624
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/expand/Conv2D + pred/MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_2/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x946eca69f99ddcb4
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/expand/Conv2D + pred/MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_2/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/expand/Conv2D + pred/MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_2/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xcc68d30459859090
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/expand/Conv2D + pred/MobilenetV2/expanded_conv_2/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_2/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xb5fdd9dd73a52c67
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_2/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/project/Conv2D + pred/MobilenetV2/expanded_conv_2/add, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/project/Conv2D + pred/MobilenetV2/expanded_conv_2/add, LayerImpl: CaskConvolution, tactic: 0xe5e256a48aae2e77
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/project/Conv2D + pred/MobilenetV2/expanded_conv_2/add, LayerImpl: CaskConvolution, tactic: 0xc72182f0fce13bb0
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_2/project/Conv2D + pred/MobilenetV2/expanded_conv_2/add, LayerImpl: CaskConvolution, tactic: 0x0129597ad9bbff14
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/expand/Conv2D + PWN(pred/MobilenetV2/expanded_conv_3/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x5e7d1125e7896624
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/expand/Conv2D + PWN(pred/MobilenetV2/expanded_conv_3/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x946eca69f99ddcb4
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/expand/Conv2D + PWN(pred/MobilenetV2/expanded_conv_3/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/expand/Conv2D + PWN(pred/MobilenetV2/expanded_conv_3/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xcc68d30459859090
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/expand/Conv2D + PWN(pred/MobilenetV2/expanded_conv_3/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xb5fdd9dd73a52c67
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_3/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xc2a5fc6b5e7cef5e
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xe5e256a48aae2e77
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xe3dc8e986f0522d1
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_3/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x0129597ad9bbff14
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/expand/Conv2D + pred/MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_4/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/expand/Conv2D + pred/MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_4/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xe5e256a48aae2e77
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/expand/Conv2D + pred/MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_4/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/expand/Conv2D + pred/MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_4/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x3bee4a098b4f8914
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/expand/Conv2D + pred/MobilenetV2/expanded_conv_4/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_4/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x3f3840edab5c9d44
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_4/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xc2a5fc6b5e7cef5e
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xded29d328f8f7228
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x21904dd9d0cd407e
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_4/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xb5fdd9dd73a52c67
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/expand/Conv2D + pred/MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_5/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x7e29bdfccd92c42c
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/expand/Conv2D + pred/MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_5/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x849891f3d1d80c55
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/expand/Conv2D + pred/MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_5/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/expand/Conv2D + pred/MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_5/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x73163c1d09e17290
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/expand/Conv2D + pred/MobilenetV2/expanded_conv_5/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_5/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xb5fdd9dd73a52c67
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_5/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xfa1e150a2da08265
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_5/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0xd297ae2cdb8b1406
WARNING: Cache result detected as invalid for node: pred/local_head/descriptor/Conv/Conv2D + pred/local_head/descriptor/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/descriptor/Conv/Relu6) || pred/local_head/detector/Conv/Conv2D + pred/local_head/detector/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/detector/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x268494f0a1c83de3
WARNING: Cache result detected as invalid for node: pred/local_head/descriptor/Conv/Conv2D + pred/local_head/descriptor/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/descriptor/Conv/Relu6) || pred/local_head/detector/Conv/Conv2D + pred/local_head/detector/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/detector/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x946eca69f99ddcb4
WARNING: Cache result detected as invalid for node: pred/local_head/descriptor/Conv/Conv2D + pred/local_head/descriptor/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/descriptor/Conv/Relu6) || pred/local_head/detector/Conv/Conv2D + pred/local_head/detector/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/detector/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x94dc70026a3bd827
WARNING: Cache result detected as invalid for node: pred/local_head/descriptor/Conv/Conv2D + pred/local_head/descriptor/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/descriptor/Conv/Relu6) || pred/local_head/detector/Conv/Conv2D + pred/local_head/detector/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/detector/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0xd46b3ee2b59f893c
WARNING: Cache result detected as invalid for node: pred/local_head/descriptor/Conv/Conv2D + pred/local_head/descriptor/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/descriptor/Conv/Relu6) || pred/local_head/detector/Conv/Conv2D + pred/local_head/detector/Conv/BatchNorm/FusedBatchNormV3 + PWN(pred/local_head/detector/Conv/Relu6), LayerImpl: CaskConvolution, tactic: 0x1dcf9babce3d9b3b
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0xa79cf41de521f476
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x399448b5af8ca81a
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x25eed4cfa195d49d
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x97afba3735828021
WARNING: Cache result detected as invalid for node: pred/local_head/detector/Conv_1/BiasAdd, LayerImpl: CaskConvolution, tactic: 0x249110624ee04937
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/expand/Conv2D + pred/MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_6/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x7e29bdfccd92c42c
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/expand/Conv2D + pred/MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_6/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xf92663d88255134b
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/expand/Conv2D + pred/MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_6/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/expand/Conv2D + pred/MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_6/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0x3bee4a098b4f8914
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/expand/Conv2D + pred/MobilenetV2/expanded_conv_6/expand/BatchNorm/FusedBatchNormV3 + PWN(pred/MobilenetV2/expanded_conv_6/expand/Relu6), LayerImpl: CaskConvolution, tactic: 0xb5fdd9dd73a52c67
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/depthwise/depthwise + PWN(pred/MobilenetV2/expanded_conv_6/depthwise/Relu6), LayerImpl: CaskConvolution, tactic: 0x50ca8db54378cbad
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x90d45931b538d74f
WARNING: Cache result detected as invalid for node: pred/MobilenetV2/expanded_conv_6/project/Conv2D, LayerImpl: CaskConvolution, tactic: 0x0ccb6665868f9bd5
ERROR: 2: [timingCache.cpp::addOp::492] Error Code 2: Internal Error (Assertion item.bestWorkSpace == i.bestWorkSpace failed. )
ERROR: 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
段错误 (核心已转储)`

不好意思有点长
还是希望得到你的帮助～

**Comment by Amrmesi** [comment]
I have cuda 11.8 and I have the same problem how did you fix that?
