### ISSUE TITLE
Missing g2o files

### ISSUE THREAD

**Issue by KaareLJensen** [LiuLimingCode/HFNet_SLAM#8]
I have been testing the ORB_SLAM3 framework and came across your framework and wanted to try it out.
Trying to build quickly ended in error as there are two files missing in the ./g2o/g2o/stuff/ folder. More specificly 'timeutil.cpp' and 'timeutil.h'?
These file exixt in the ORB_SLAM3 repo.
Managed to build g2o after manually copying the file into the above mentioned folder.

**Comment by LiuLimingCode** [comment]
Sorry for this; files have been added.
